// Copyright 2026 Paul Biondich and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Beer struct {
	Id              int     `json:"id"`
	Slug            string  `json:"slug"`
	Name            string  `json:"name"`
	Brewery         string  `json:"brewery"`
	BrewerySlug     string  `json:"brewery_slug"`
	Style           string  `json:"style"`
	Abv             float64 `json:"abv"`
	Ibu             float64 `json:"ibu"`
	Rating          float64 `json:"rating"`
	RatingCount     int     `json:"rating_count"`
	RatingPresent   bool    `json:"rating_present"`
	RatingNote      string  `json:"rating_note"`
	Description     string  `json:"description"`
	Url             string  `json:"url"`
	CheckinsTotal   int     `json:"checkins_total"`
	CheckinsUnique  int     `json:"checkins_unique"`
	CheckinsMonthly int     `json:"checkins_monthly"`
}

type BeerListItem struct {
	Id            int     `json:"id"`
	Name          string  `json:"name"`
	Style         string  `json:"style"`
	Abv           float64 `json:"abv"`
	Ibu           float64 `json:"ibu"`
	Rating        float64 `json:"rating"`
	RatingCount   int     `json:"rating_count"`
	RatingPresent bool    `json:"rating_present"`
	Url           string  `json:"url"`
}

type BeerSearchHit struct {
	Bid         int     `json:"bid"`
	BeerName    string  `json:"beer_name"`
	BreweryName string  `json:"brewery_name"`
	BreweryId   int     `json:"brewery_id"`
	BeerSlug    string  `json:"beer_slug"`
	TypeName    string  `json:"type_name"`
	BeerAbv     float64 `json:"beer_abv"`
	BeerIbu     float64 `json:"beer_ibu"`
	RatingScore float64 `json:"rating_score"`
	RatingCount int     `json:"rating_count"`
}

type Brewery struct {
	Id            int     `json:"id"`
	Slug          string  `json:"slug"`
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	Location      string  `json:"location"`
	Rating        float64 `json:"rating"`
	RatingCount   int     `json:"rating_count"`
	RatingPresent bool    `json:"rating_present"`
	BeerCount     int     `json:"beer_count"`
	Url           string  `json:"url"`
}

type BrewerySearchHit struct {
	BreweryId        int    `json:"brewery_id"`
	BreweryName      string `json:"brewery_name"`
	BreweryPageUrl   string `json:"brewery_page_url"`
	BreweryCity      string `json:"brewery_city"`
	BreweryState     string `json:"brewery_state"`
	BreweryCountry   string `json:"brewery_country"`
	BreweryType      string `json:"brewery_type"`
	BreweryBeerCount int    `json:"brewery_beer_count"`
}
