// Copyright 2026 Paul Biondich and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBeerSearchCmd(flags *rootFlags) *cobra.Command {
	var bodyQuery string
	var bodyHitsPerPage int
	var bodyLimit int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "search",
		Short:       "Search public beers via Untappd's frontend Algolia index (search-only key published on untappd.com/search).",
		Example:     "  untappd-pp-cli beer search --query \"Hop Butcher Put On the Glasses\" --agent",
		Annotations: map[string]string{"pp:endpoint": "beer.search", "pp:method": "POST", "pp:path": "https://9WBO4RQ3HO-dsn.algolia.net/1/indexes/beer/query", "mcp:read-only": "true", "pp:requires-input": "true", "pp:happy-args": "--query=Cool Bay Hop Butcher;--limit=5"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				q, qerr := searchQueryFrom(cmd, args, bodyQuery)
				if qerr != nil && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "query")
				}
				bodyQuery = q
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			var data json.RawMessage
			var statusCode int
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				path := "https://9WBO4RQ3HO-dsn.algolia.net/1/indexes/beer/query"
				data, statusCode, err = c.PostQueryWithParamsAndHeaders(cmd.Context(), path, map[string]string{}, jsonBody, algoliaSearchHeaders())
				if err != nil {
					return classifyAPIError(cmd.OutOrStdout(), err, flags)
				}
				if !flags.dryRun {
					data, err = normalizeBeerSearchHits(data)
					if err != nil {
						return err
					}
				}
			} else {
				data, err = runBeerSearch(cmd.Context(), c, bodyQuery, searchLimitFromFlags(cmd, bodyLimit, bodyHitsPerPage))
				if err != nil {
					return classifyAPIError(cmd.OutOrStdout(), err, flags)
				}
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"}, map[string]bool{"name": true, "brewery": true, "rating": true, "rating_count": true, "url": true})
				}
				return nil
			}
			_ = statusCode
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"name": true, "brewery": true, "style": true, "abv": true, "ibu": true, "rating": true, "rating_count": true, "url": true})
		},
	}
	cmd.Flags().StringVar(&bodyQuery, "query", "", "Beer search query.")
	cmd.Flags().IntVar(&bodyLimit, "limit", 10, "Max matches to return (polite default 10).")
	cmd.Flags().IntVar(&bodyHitsPerPage, "hits-per-page", 10, "Deprecated alias for --limit")
	_ = cmd.Flags().MarkHidden("hits-per-page")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
