// Copyright 2026 Paul Biondich and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBeerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "beer",
		Short:       "Public beer pages and search — name, brewery, style, ABV, IBU, global rating, rating count, description",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBeerGetCmd(flags))
	cmd.AddCommand(newBeerSearchCmd(flags))
	return cmd
}
