// Copyright 2026 Paul Biondich and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBreweryBeersCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "beers <slug>",
		Short:       "List beers on a public brewery beer page, including ratings when present.",
		Example:     "  untappd-pp-cli brewery HopButcher beers --agent",
		Annotations: map[string]string{"pp:endpoint": "brewery.beers", "pp:method": "GET", "pp:path": "/{slug}/beer", "mcp:read-only": "true", "pp:happy-args": "slug=HopButcher"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <slug>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <slug>"))
			}
			path := "/{slug}/beer"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("slug is required\nUsage: %s <%s>", cmd.CommandPath(), "slug"))
			}
			path = replacePathParam(path, "slug", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := htmlHeaders()

			params := map[string]string{}
			data, err := c.GetWithHeaders(cmd.Context(), path, params, headerOverrides)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"}, map[string]bool{"id": true, "name": true, "rating": true, "rating_count": true, "url": true})
				}
				return nil
			}
			if !flags.dryRun {
				data, err = parseBreweryBeersHTML(data)
				if err != nil {
					return err
				}
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"id": true, "name": true, "rating": true, "rating_count": true, "url": true})
		},
	}

	return cmd
}
